language: R
cache: packages
sudo: false

warnings_are_errors: false

r:
  - release
  
bioc_required: true
bioc_packages:
  - flowCore
  - flowViz

before_deploy:
  - R -e "install.packages('roxygen2', repos = 'http://cran.rstudio.com')"
  - R -e "staticdocs::build_site(examples = TRUE)"


r_github_packages:
  - FMKerckhof/flowFDA
  
r_check_args: "--no-vignettes"
  
script: 
  - |
    travis_wait 30 R CMD build --no-build-vignettes .
    travis_wait 20 R CMD check --no-examples --no-build-vignettes Phenoflow*tar.gz
